/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#ddb7ff",
        "on-surface": "#111111",
        "surface-dim": "#eeebe6",
        "secondary-fixed": "#f0dbff",
        "primary-fixed": "#d8e2ff",
        "outline": "#8c909f",
        "surface-container": "#f5f3f0",
        "on-background": "#111111",
        "tertiary-container": "#df7412",
        "secondary-container": "#6f00be",
        "on-tertiary-fixed-variant": "#723600",
        "on-tertiary-container": "#461f00",
        "surface": "#eeebe6",
        "inverse-primary": "#005ac2",
        "background": "#eeebe6",
        "inverse-on-surface": "#283044",
        "surface-bright": "#ffffff",
        "surface-container-high": "#e5e2dd",
        "on-tertiary-fixed": "#311400",
        "on-primary-fixed": "#001a42",
        "tertiary": "#ffb786",
        "tertiary-fixed": "#ffdcc6",
        "outline-variant": "#424754",
        "tertiary-fixed-dim": "#ffb786",
        "surface-tint": "#adc6ff",
        "surface-container-highest": "#dbd8d3",
        "surface-variant": "#2d3449",
        "on-primary-fixed-variant": "#004395",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#adc6ff",
        "on-error": "#690005",
        "secondary-fixed-dim": "#ddb7ff",
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "inverse-surface": "#dae2fd",
        "primary": "#111111",
        "on-tertiary": "#502400",
        "on-surface-variant": "#666666",
        "on-secondary-fixed-variant": "#6900b3",
        "on-secondary": "#490080",
        "on-secondary-container": "#d6a9ff",
        "on-secondary-fixed": "#2c0051",
        "surface-container-low": "#efece8",
        "surface-container-lowest": "#fcfaf8",
        "error-container": "#93000a",
        "error": "#ffb4ab"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "1.5rem",
        "stack-lg": "4rem",
        "gutter": "2rem",
        "stack-md": "1.5rem",
        "stack-sm": "0.5rem",
        "margin-desktop": "4rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};
